// <auto-generated />
using System;
using Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260604171331_AddAuditEvents")]
    partial class AddAuditEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Database.Entities.AuditEventEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActorClinicCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorCredentialId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorCredentialLabel")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorSessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityDisplay")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ip")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("OccurredAtUnixTimeMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUnixTimeMilliseconds");

                    b.HasIndex("ActorClinicCode", "OccurredAtUnixTimeMilliseconds");

                    b.HasIndex("EntityType", "EntityId");

                    b.HasIndex("ServiceName", "Operation", "OccurredAtUnixTimeMilliseconds");

                    b.ToTable("AuditEvents");
                });

            modelBuilder.Entity("Database.Entities.ClientEntity", b =>
                {
                    b.Property<string>("Nickname")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyIdentifier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RepresentativeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VatIdentifier")
                        .HasColumnType("TEXT");

                    b.HasKey("Nickname");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Database.Entities.InvoiceEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BankBic")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BankIban")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BuyerAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BuyerCity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BuyerCompanyIdentifier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BuyerCountry")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BuyerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BuyerPostalCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BuyerRepresentativeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BuyerVatIdentifier")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCorrected")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLegacy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("NumberNumeric")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SellerAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SellerCity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SellerCompanyIdentifier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SellerCountry")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SellerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SellerPostalCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SellerRepresentativeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SellerVatIdentifier")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.HasIndex("NumberNumeric")
                        .IsUnique();

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("Database.Entities.InvoiceLineItemEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmountCents")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("InvoiceEntityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceEntityId");

                    b.ToTable("InvoiceLineItems");
                });

            modelBuilder.Entity("Database.Entities.InvoiceSequenceEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("InvoiceSequence", null, t =>
                        {
                            t.HasCheckConstraint("CK_InvoiceSequence_Id", "Id = 1");
                        });
                });

            modelBuilder.Entity("Database.Entities.SchedulingAuthSessionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("AbsoluteExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClinicCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedIp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedUserAgent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CredentialId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("ClinicCode", "CredentialId");

                    b.ToTable("SchedulingAuthSessions");
                });

            modelBuilder.Entity("Database.Entities.SchedulingOrderEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AbutmentTeeth")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CaseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClinicCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClinicDisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConstructionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUnixTimeMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedIp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedUserAgent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CredentialId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CredentialLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CredentialPinHashFingerprint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ImpressionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("RequestedDeliveryDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Shade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ToothEnd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ToothStart")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClinicCode");

                    b.HasIndex("CreatedAtUnixTimeMilliseconds");

                    b.HasIndex("OrderCode")
                        .IsUnique();

                    b.HasIndex("RequestedDeliveryDate");

                    b.HasIndex("Status");

                    b.ToTable("SchedulingOrders");
                });

            modelBuilder.Entity("Database.Entities.InvoiceLineItemEntity", b =>
                {
                    b.HasOne("Database.Entities.InvoiceEntity", "Invoice")
                        .WithMany("LineItems")
                        .HasForeignKey("InvoiceEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("Database.Entities.InvoiceEntity", b =>
                {
                    b.Navigation("LineItems");
                });
#pragma warning restore 612, 618
        }
    }
}
