// <auto-generated />
using System;
using Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260223194827_AddInvoiceIsCorrected")]
    partial class AddInvoiceIsCorrected
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Database.Entities.ClientEntity", b =>
                {
                    b.Property<string>("Nickname")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyIdentifier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RepresentativeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VatIdentifier")
                        .HasColumnType("TEXT");

                    b.HasKey("Nickname");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Database.Entities.InvoiceEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BankBic")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BankIban")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BuyerAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BuyerCity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BuyerCompanyIdentifier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BuyerCountry")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BuyerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BuyerPostalCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BuyerRepresentativeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BuyerVatIdentifier")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCorrected")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("NumberNumeric")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SellerAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SellerCity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SellerCompanyIdentifier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SellerCountry")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SellerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SellerPostalCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SellerRepresentativeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SellerVatIdentifier")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.HasIndex("NumberNumeric")
                        .IsUnique();

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("Database.Entities.InvoiceLineItemEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmountCents")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("InvoiceEntityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceEntityId");

                    b.ToTable("InvoiceLineItems");
                });

            modelBuilder.Entity("Database.Entities.InvoiceSequenceEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("InvoiceSequence", null, t =>
                        {
                            t.HasCheckConstraint("CK_InvoiceSequence_Id", "Id = 1");
                        });
                });

            modelBuilder.Entity("Database.Entities.InvoiceLineItemEntity", b =>
                {
                    b.HasOne("Database.Entities.InvoiceEntity", "Invoice")
                        .WithMany("LineItems")
                        .HasForeignKey("InvoiceEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("Database.Entities.InvoiceEntity", b =>
                {
                    b.Navigation("LineItems");
                });
#pragma warning restore 612, 618
        }
    }
}
